feat footer
Likelion-YeungNam-Univ/tireso-web pull request #5
Opened 2023-08-05 16:25 UTC by KangRokYoon

footer 구현했습니다. 폰트도 추가했고 이것저것 해봤는데 쉽지가 않네요. .... 구현한 부분도 약간 문제가 좀 있는 거 같아서 다른 부분도 추가하면서 확인해 봐야 할 것 같습니다.

2023-08-05 16:28 UTC, subihawng approved these changes

2023-08-05 16:29 UTC, byeon22 requested changes
강록님! 저 이미지 넣으면서 발견한 충돌이 있는데..!! svg 파일 피그마에서 바로 다운 받으면 <pattern> 태그에 있는 id가 기본적으로 pattern0으로 설정되어서 처음 설정한 타이어로고가 계속 나오더라구요ㅠㅠ 그래서 <patter> 태그에 있는 id랑 url 변경해주는 게 좋을 것 같습니당!!

2023-08-06 15:58 UTC, byeon22 approved these changes

2023-08-06 15:58 UTC, byeon22 commented on src/assets/images/FooterLogo.svg
> +<rect width="124" height="38" fill="url(#pattern1)"/>
여기랑!

2023-08-06 15:58 UTC, byeon22 commented on src/assets/images/FooterLogo.svg
> +<pattern id="pattern0" patternContentUnits="objectBoundingBox" width="1" height="1">
여기에 있습니당!!

2023-08-06 15:59 UTC, merged